package app.cash.better.dynamic.features.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

abstract class GenerateExternalResourcesTask : DefaultTask() {
  @get:OutputDirectory
  abstract val outputDirectory: DirectoryProperty

  @get:Input
  abstract val declarations: ListProperty<String>

  @TaskAction
  fun generateResources() {
    val outputFile = File(outputDirectory.asFile.get(), "values/externals.xml")
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
      """
      |<?xml version="1.0" encoding="utf-8"?>
      |<!-- Generated by the Better Dynamic Features plugin. -->
      |<resources>
      |${declarations.get().joinToString(separator = "\n") { """  <style name="$it" />""" }}
      |</resources>
      """.trimMargin(),
    )
  }
}
