/*
 * Copyright (C) 2023 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package app.cash.better.dynamic.features.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

abstract class GenerateExternalResourcesTask : DefaultTask() {
  @get:OutputDirectory
  abstract val outputDirectory: DirectoryProperty

  @get:Input
  abstract val declarations: ListProperty<String>

  @TaskAction
  fun generateResources() {
    val outputFile = File(outputDirectory.asFile.get(), "values/externals.xml")
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
      """
      |<?xml version="1.0" encoding="utf-8"?>
      |<!-- Generated by the Better Dynamic Features plugin. -->
      |<resources>
      |${declarations.get().joinToString(separator = "\n") { """  <style name="$it" />""" }}
      |</resources>
      """.trimMargin(),
    )
  }
}
